//! The Android library (libnorimusic.so): the core, its uniffi scaffolding for the Kotlin bindings, and the
//! JNI doors the calls made per buffer, per frame or per list row go through. Nothing here decides
//! anything; each door turns Java's arguments into the core's and back.
//!
//! The scaffolding is generated by build.rs (uniffi-bindgen-kotlin-jni) as JNI functions the generated
//! Kotlin finds by their `Java_uniffi_Scaffolding_` names. Its own `JNI_OnLoad` is renamed there to
//! `uniffi_on_load`, and ours calls it.
//!
//! Every door is registered by `JNI_OnLoad` with `RegisterNatives` rather than found by its `Java_` name:
//! the first call skips the symbol search, the functions stay out of the library's exports, and doors
//! whose arguments are all primitives can be `@CriticalNative`, which Android 8 to 11 only honour for
//! registered methods. A critical door takes neither the `JNIEnv` nor the class.

use std::ffi::{c_void, CStr};

use jni::objects::JString;
use jni::sys::{jint, jstring, JNINativeMethod, JNI_ERR, JNI_OK, JNI_VERSION_1_6};
use jni::JNIEnv;

include!(concat!(env!("OUT_DIR"), "/uniffi_bindgen_kotlin_jni.uniffi.rs"));

/// The Rust heap, counted for the perf report's memory line (nori_model::heap): a relaxed add per
/// allocation and per free.
#[global_allocator]
static HEAP: nori_core::heap::Counting = nori_core::heap::Counting;

mod covers;
mod dsp;
mod heard;
mod look;
mod measure;
mod mediacodec;
mod player;
mod playlist;
mod seek;
mod settings;
mod stream_cache;
mod track;
mod transfers;

/// One Kotlin class and the natives it declares.
pub(crate) struct Class {
    /// The class that declares the methods, as `FindClass` names it: for a Kotlin `object` with
    /// `@JvmStatic external fun`, the object's own class.
    name: &'static CStr,
    methods: &'static [Native],
}

pub(crate) struct Native {
    name: &'static CStr,
    sig: &'static CStr,
    f: *const c_void,
}

// SAFETY: a `Native` only holds a function's address, which never changes and is only read.
unsafe impl Sync for Native {}

/// A native method: its name, its JVM signature and the function behind it.
macro_rules! native {
    ($name:literal, $sig:literal, $f:expr) => {
        $crate::Native { name: $name, sig: $sig, f: $f as *const ::std::ffi::c_void }
    };
}
pub(crate) use native;

static CLASSES: [&Class; 15] = [
    &covers::CLASS,
    &dsp::CLASS,
    &heard::HEARD,
    &heard::PLAYHEAD,
    &look::COVER,
    &look::LYRICS,
    &measure::CLASS,
    &player::CLASS,
    &playlist::CLASS,
    &seek::CLASS,
    &settings::EQ_BANDS,
    &settings::SOUND_EDIT,
    &stream_cache::CLASS,
    &transfers::DOWNLOADS,
    &transfers::LINES,
];

/// Hands the JavaVM and the app's class loader to the uniffi scaffolding, then registers every door. A
/// class or method that cannot be found - R8 took it out of a build that never calls it - is left out and
/// said in the log; the rest are registered all the same.
#[no_mangle]
pub extern "system" fn JNI_OnLoad(vm: jni::JavaVM, _: *mut c_void) -> jint {
    let Ok(mut env) = vm.get_env() else { return JNI_ERR };
    // SAFETY: both pointers are the live JavaVM and this thread's JNIEnv; the two jni-sys versions describe
    // the same C structures.
    unsafe {
        uniffi_bindgen_kotlin_jni_scaffolding::uniffi_on_load(vm.get_java_vm_pointer().cast(), std::ptr::null_mut());
        // The scaffolding looks its classes up the first time it needs them, which may be on a thread the
        // core started; `FindClass` there only sees the system's classes. This thread sees the app's, so
        // the runtime keeps their loader for those lookups.
        if !uniffi_bindgen_kotlin_jni_runtime::remember_class_loader(env.get_raw().cast(), c"uniffi/UniffiKt") {
            nori_core::alog::info("jni: no uniffi/UniffiKt; callbacks from the core's own threads will fail");
        }
    }
    // HE-AAC for the Rust engine, through the platform's decoder.
    mediacodec::lend();
    for class in CLASSES {
        register(&mut env, class);
    }
    watch();
    nori_core::heap::Counting::installed();
    nori_perf::memory::install(engine_memory);
    JNI_VERSION_1_6
}

/// What the engine holds, for the perf report's memory line (nori_perf::memory): read at a stretch's ends.
fn engine_memory() -> nori_perf::memory::EngineMemory {
    let songs = nori_engine::source::held();
    nori_perf::memory::EngineMemory {
        songs: songs.songs as i32,
        songs_kb: (songs.bytes / 1024) as i64,
        songs_on_disk: songs.on_disk as i32,
        ring_kb: (nori_engine::output::ring_bytes() / 1024) as i64,
        model_kb: (nori_engine::core::beat_model_bytes() / 1024) as i64,
    }
}

/// The engine tells the perf build's invariant watch what each wake of its thread saw
/// (nori_engine::watch, nori_perf::invariants): asked of an atomic per wake, and only while it is on.
fn watch() {
    nori_engine::watch::install(nori_engine::watch::Hook {
        wanted: nori_perf::invariants::on,
        seen: |s| nori_perf::invariants::engine_seen(s.now_ms, s.playing, s.offloaded, s.index, s.position_ms, s.in_output_ms, &s.state),
    });
}

/// Whatever Java threw is written to the log and cleared: a thread of ours has nobody to throw it to.
pub(crate) fn cleared(env: &mut JNIEnv) {
    if env.exception_check().unwrap_or(false) {
        let _ = env.exception_describe();
        let _ = env.exception_clear();
    }
}

/// This thread's JNIEnv, the thread attached to the JVM under its own name ("nori-track", "nori-load")
/// for the rest of its life and detached when it ends. Attached without a name, as the jni crate does it,
/// the JVM renamed every thread of ours "Thread-NN", and a thread list could not tell them apart.
pub(crate) fn attached(vm: &'static jni::JavaVM) -> Option<JNIEnv<'static>> {
    if let Ok(env) = vm.get_env() {
        return Some(env);
    }
    // SAFETY: the live JavaVM; the two jni-sys versions describe the same C structures.
    let ok = unsafe { uniffi_bindgen_kotlin_jni_runtime::attach_for_life(vm.get_java_vm_pointer().cast()) };
    if ok { vm.get_env().ok() } else { None }
}

fn register(env: &mut JNIEnv, class: &Class) {
    let raw = env.get_raw();
    // SAFETY: `raw` is the live JNIEnv of the thread loading the library, and every name and signature is
    // a NUL-terminated string that lives for the whole program.
    unsafe {
        let jni = &**raw;
        let found = (jni.FindClass.unwrap())(raw, class.name.as_ptr());
        if found.is_null() {
            (jni.ExceptionClear.unwrap())(raw);
            nori_core::alog::info(&format!("jni: no class {:?}", class.name));
            return;
        }
        let methods: Vec<JNINativeMethod> =
            class.methods.iter().map(|m| JNINativeMethod { name: m.name.as_ptr() as *mut _, signature: m.sig.as_ptr() as *mut _, fnPtr: m.f as *mut _ }).collect();
        if (jni.RegisterNatives.unwrap())(raw, found, methods.as_ptr(), methods.len() as jint) != JNI_OK {
            (jni.ExceptionClear.unwrap())(raw);
            // One at a time, so a single missing method does not take the class's others with it.
            for (m, native) in methods.iter().zip(class.methods) {
                if (jni.RegisterNatives.unwrap())(raw, found, m, 1) != JNI_OK {
                    (jni.ExceptionClear.unwrap())(raw);
                    nori_core::alog::info(&format!("jni: no method {:?}.{:?}{:?}", class.name, native.name, native.sig));
                }
            }
        }
        (jni.DeleteLocalRef.unwrap())(raw, found);
    }
}

/// `s` as a Java string, or null if the JVM could not make one (it has then thrown).
pub(crate) fn java_string(env: &JNIEnv, s: &str) -> jstring {
    env.new_string(s).map_or(std::ptr::null_mut(), JString::into_raw)
}

/// A Java string's contents, for as long as the closure runs; `None` for a null reference.
pub(crate) fn with_str<R>(env: &JNIEnv, s: &JString, f: impl FnOnce(&str) -> R) -> Option<R> {
    if s.is_null() {
        return None;
    }
    // SAFETY: every door is registered with RegisterNatives under a signature whose parameter is a
    // java.lang.String, so the JVM has checked the type already. jni's checked `get_string` would look the
    // String class up, ask for the object's class and compare them on every call, leaving two local
    // references behind, for an answer that cannot change.
    let v = unsafe { env.get_string_unchecked(s) }.ok()?;
    let v: std::borrow::Cow<str> = (&v).into();
    Some(f(&v))
}

/// A Java string's contents as an owned `String`; `None` for a null reference.
pub(crate) fn string(env: &JNIEnv, s: &JString) -> Option<String> {
    with_str(env, s, str::to_string)
}
